# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: iThrive
email: laura@ithrive.net.au
description: >
  iThrive provides pilates and massage service to Manly and the greater Sydney Northern Beaches.
  Both home visit and studio options available.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ithrive.net.au" # the base hostname & protocol for your site, e.g. http://example.com
# twitter:
#   username: ...
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
logo: "https://ithrive.net.au/images/site-logo.jpg"
github_username: ithrive
author: Laura Kavanagh
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
social:
  name: Laura Kavanagh
  links:
    - https://www.facebook.com/ithrivemanly
google_site_verification: RhF5lLeJQO2xlrXR7urKO_RlcoKB8CyFBn6xbGwBLdE
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

permalink: "/posts/:year/:title.html"

paginate: 10
paginate_path: "/posts/page:num/"

# service keys
gtagKey: "GTM-5H8DFSZ"
shareThisKey: "5ca81c026f05b20011c6da24"
disqusShortName: "ithrive"
googleMapAPIKey: "AIzaSyCOs4V5JHvC2_CQS6CJV26UH43w-3G2Dao"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - readme.md
collections:
  info:
    output: true
    permalink: /info/:path/
  events:
    output: false
defaults:
  - scope:
      collection: info
    values:
      layout: info
  - scope:
      type: posts
    values:
      layout: post
  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/default-card.png

# https://github.com/penibelst/jekyll-compress-html
# http://rich-knight.com/articles/compressing-html-in-jekyll/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
